# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
 defaults: &defaults
   working_directory: ~/code
   docker:
     - image: circleci/node:10
       environment:
         NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
         JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

 version: 2
 jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - run: npm i
       - run: bower install
       - run: npm run eslint:ci
